# Generated by Django 2.2.2 on 2019-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crawl_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('post_time', models.CharField(max_length=255)),
                ('blog_text', models.TextField()),
                ('check_in_location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'crawl_blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_gender', models.CharField(max_length=255)),
                ('user_place', models.CharField(max_length=255)),
                ('user_label', models.CharField(max_length=255)),
                ('user_introduction', models.CharField(max_length=255)),
                ('user_birthday', models.CharField(max_length=255)),
                ('user_sentiment', models.CharField(max_length=255)),
                ('user_authentication', models.CharField(max_length=255)),
                ('user_study', models.CharField(max_length=255)),
                ('user_work', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
